feat: добавлен Clickhouse
xh4vm/ugc pull request #1
Opened 2022-11-30 13:33 UTC by xczdenis

В докер компоузе сделан отдельный профайл: `clickhouse`

Важно: в папку `backend/clickhouse/fake_data` нужно поместить файл `ratings.csv` (см. ридми в этой папке)

Как запустить:
1. Перенести все переменные окружения секции #Clickhouse section из .env.example в .env
2. Команда `make build-dockers-ch` соберет и запустит кластер кликхауса в докере. В кластере будут созданы базы данных
3. Команда `make ch-db-upgrade` выполнит обновление схемы баз данных (будут созданы все таблицы)
4. Команда `make ch-load` загрузит в кликхаус датасет `ratings.csv` из папки `fake_data`
5. Команда `make ch-benchmark` запустит выполнение запросов и покажет время их выполнения

2022-12-01 07:00 UTC, xh4vm requested changes

2022-12-01 14:19 UTC, xczdenis commented on backend/clickhouse/src/adapters/clickhouse/client.py
> +        r = self.execute("SHOW DATABASES") or []
готово

2022-12-02 06:15 UTC, xczdenis commented on backend/clickhouse/src/adapters/clickhouse/client.py
> +            self.create_table(self.db_name, models.View)
готово

2022-12-02 06:17 UTC, xczdenis commented on backend/clickhouse/src/adapters/clickhouse/client.py
> +class ClickHouseClient(BaseDBClient):
исправил так: теперь есть 2 класса:
1. BaseDBClient - занимается только подключением к серверу и выполнением запроса (не важно какого запроса, просто метод execute)
2. BaseDBMigrator - занимается всем, что связано с изменением схемы базы данных

2022-12-02 07:19 UTC, xczdenis commented on backend/clickhouse/src/adapters/base.py
> +@dataclass
решили оставить датаклассами

2022-12-02 07:20 UTC, xczdenis commented on backend/clickhouse/src/benchmarks.py
> +    print(query)
готово

2022-12-02 07:20 UTC, xczdenis commented on backend/clickhouse/src/benchmarks.py
> +    """SELECT COUNT(*) FROM views_progress"""
готово

2022-12-02 07:23 UTC, xczdenis commented on backend/clickhouse/src/load_data.py
> +FILE_NAME = "ratings.csv"
BENCH_SIZE сделал через настройки, но вот FILE_NAME - с ним сложнее. Дело в том, что load_data.py - это очень фейковый модуль, очень захардкоженый, в нем загрузка данных настроена исключительно на файл структуры ratings.csv. Если этот файл выносить в настройки, тогда подразумевается, что можно загрузить любой файл, любой - а это целый отдельный проект.

2022-12-02 07:23 UTC, xczdenis commented on backend/clickhouse/src/load_data.py
> +    for row in reader:
класс! совсем забыл про него) по старинке увеличиваю счетчики.

2022-12-02 07:27 UTC, xczdenis commented on backend/clickhouse/src/load_data.py
> +        frame = random.randint(1, 7200)
Извини, я это не сделал, хотя сам об этом думал( Кароче тут прикол в том, что для того чтобы это сделать нормально функцией с декоратором, который время будет засекать, надо разбивать исходный файл на пачки и обрабатывать пачки - тогда все красиво будет. Но, для упрощения, я просто перебираю исходный файл построчно и под for делаю проверку `if current_bench_size == BENCH_SIZE - 1` то пошла новая пачка. Из-за этого не получается снаскока передлать на отдельную функцию

2022-12-02 07:27 UTC, xczdenis commented on backend/clickhouse/src/load_data.py
> +            total_benches += 1
готово

2022-12-02 07:28 UTC, xczdenis commented on backend/clickhouse/src/load_data.py
> +        insert_to_db(field_values[:-2])
потому что сзади остается запятая и пробел: `f"(... now()), "`

2022-12-02 07:28 UTC, xczdenis commented on backend/clickhouse/src/load_data.py
> +print("Всего пачек:", total_benches)
готово

2022-12-02 07:28 UTC, xczdenis commented on backend/clickhouse/docker/zk-config/zoo.cfg
> +clientPort=2182
сделал. использую образ bitmani

2022-12-02 07:29 UTC, xczdenis commented on backend/clickhouse/src/load_data.py
> +end = datetime.datetime.now()
готово

2022-12-02 07:29 UTC, xczdenis commented on backend/clickhouse/src/load_data.py
> +BENCH_SIZE = 1000000
готово

2022-12-02 09:38 UTC, xh4vm approved these changes
LGTM 👍

2022-12-02 09:40 UTC, merged